### ISSUE TITLE
Import additional RDS/Aurora cloudwatch metrics

### ISSUE THREAD

**Issue by asher** [Netflix/atlas#1002]
Please add the following Aurora specific cloudtrail metrics to the list of RDS metrics imported to atlas:

`AuroraReplicaLag`
`AuroraReplicaLagMaximum`
`FreeLocalStorage`

**Comment by zimmermatt** [comment]
`FreeLocalStorage` is already available as `aws.rds.diskFree`.

https://github.com/Netflix/atlas/blob/master/atlas-poller-cloudwatch/src/main/resources/rds.conf#L32-L34
