### ISSUE TITLE
Missing aws lambda metrics

### ISSUE THREAD

**Issue by JonathanBond** [Netflix/atlas#1005]
Could you please add the aws lambda metrics IteratorAge, DeadLetterErrors, ConcurrentExecution and UnreservedConcurrentExecutions.  Thanks, JB

**Comment by zimmermatt** [comment]
Discussed with @JonathanBond. He's going to set up a sample, so we can verify the dimensions on these.

**Comment by bondj** [comment]
DeadLetterErrors is {
    "view": "timeSeries",
    "stacked": false,
    "metrics": [
        [ "AWS/Lambda", "DeadLetterErrors", "FunctionName", "multiRegion-function1-prod-prod", "Resource", "multiRegion-function1-prod-prod:$LATEST" ]
    ],
    "region": "us-east-1"
}
