### ISSUE TITLE
how does atlas work with zuul2？

### ISSUE THREAD

**Issue by qtwang** [Netflix/atlas#1041]

**Comment by brharrington** [comment]
The zuul code base is instrumented using [Spectator](https://github.com/Netflix/spectator). When they run internally the registry binding is set to use AtlasRegistry to report to Atlas. Similar to [this example](https://github.com/Netflix-Skunkworks/iep-apps/blob/master/iep-atlas/README.md) running an instance of Atlas that reports to itself.

**Comment by qtwang** [comment]
I set "netflix.atlas.uri: http://127.0.0.1:7101/api/v1/publish/",but the result is "path not found: /api/v1/publish",  so how to register to atlas? 
thanks a lot!!

**Comment by qtwang** [comment]
@brharrington I set "netflix.atlas.uri: http://127.0.0.1:7101/api/v1/publish/",but the result is "path not found: /api/v1/publish", so how to register to atlas?
thanks a lot!!

**Comment by brharrington** [comment]
I'm guessing you didn't specify the memory conf when running Atlas, see:

https://github.com/Netflix/atlas/wiki/Getting-Started#running-demo-with-memory-storage

**Comment by qtwang** [comment]
@brharrington thank you, according to your suggestion, I run Atlas with the memory conf successfully,but I register a example to atlas based on spring-cloud-starter-atlas.
I just want to know how to register Spectator to Atlas without spring cloud,see: 
http://netflix.github.io/spectator/en/latest/intro/netflix/
it maybe need atlas-client,but I can't find netflix:atlas-client:latest.release in maven ,
could you give me a detail example?

**Comment by brharrington** [comment]
> I just want to know how to register Spectator to Atlas without spring cloud

There is an example linked in https://github.com/Netflix/atlas/issues/1041#issuecomment-492904585 that does not use spring cloud. The `atlas-client` library is not needed for that example.
