### ISSUE TITLE
what is the best way to package the app?

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#113]
So far looked at:
- Simple standalone package for use with the examples and getting started easily. The single jar works well for this.
- Packaging with other jars and configs. Zero to cloud examples use gradle to add addtional jars and build a deb/rpm on the fly (https://github.com/brharrington/zerotocloud)

Current assumption is for non-toy use-cases we'll need to pull in some additional jars and configs.

**Comment by koshelev** [comment]
Probably [SBT Native Packager Plugin](http://www.scala-sbt.org/sbt-native-packager/) can help? It can build standalone jar, deb/rpm, docker image.

**Comment by andysworkshop** [comment]
Don't package it at all as a standalone. Whichever method you choose will only satisfy some percentage of the user base. For example I'm currently deconstructing the 1.4.6 fat jar and repackaging it as a spring boot application which just about works although it's clear that it's not meant to be launched like that.

I'd vote for making the core jars and configurations available as artifacts and document the APIs required to start it up as a server and then call into it to access the functionality. It'd be nice if it played well with Spring boot as well - in 1.4.6 they both want to initialize the Netflix configuration system and only Spring has a guard against calling it twice.

**Comment by brharrington** [comment]
> Don't package it at all as a standalone. Whichever method you choose will only satisfy some percentage of the user base. For example I'm currently deconstructing the 1.4.6 fat jar

Just to be clear, you can get them now as a maven dependency using the jcenter repo, e.g.:

http://jcenter.bintray.com/com/netflix/atlas_v1/atlas-core/1.4.6/

We only provide the standalone as a convenient example without having to go through a build system.

> It'd be nice if it played well with Spring boot as well - in 1.4.6 they both want to initialize the Netflix configuration system and only Spring has a guard against calling it twice.

First I have heard about this. Is there an issue or something you can point me at that discusses the problem?

**Comment by brharrington** [comment]
There is a simple example of packaging up as a deb:

https://github.com/Netflix-Skunkworks/iep-apps/tree/master/iep-atlas
