### ISSUE TITLE
memory.conf doesn't appear to effect configuration in standalone

### ISSUE THREAD

**Issue by Chomeh** [Netflix/atlas#1135]
If I follow the getting started guide, https://github.com/Netflix/atlas/wiki/Getting-Started but use 1.6.x resources (https://raw.githubusercontent.com/Netflix/atlas/v1.6.x/conf/memory.conf, and https://github.com/Netflix/atlas/releases/download/v1.6.3/atlas-standalone-1.6.3.jar), when I query for a a graph, the step size comes back as 1m rather than the 10s in memory.conf. Working backwards I found 1.6.0-rc8 to be the oldest version where changing the values in memory.conf had an effect.

**Comment by brharrington** [comment]
Thanks for the report, I'll take a look when I get a chance.
