### ISSUE TITLE
Method not allowed: POST

### ISSUE THREAD

**Issue by ktechmidas** [Netflix/atlas#1146]
Trying to follow the Getting Started guide here: https://github.com/Netflix/atlas/wiki/Getting-Started

Only thing I'm doing different is I have a later version (1.6.4) and the latest memory.conf but when I use it I get the following (even though I'm not POSTing)

```
curl -s 'http://localhost:7101/api/v1/tags'
{"type":"error","message":"method not allowed: POST"}%      
```
And this is appearing in the logs:

`2020-02-27T17:22:18.817 DEBUG [atlas-akka.actor.default-dispatcher-3] com.netflix.spectator.ipc.IpcLogger: {"owner":"atlas-akka","start":1582795338816,"latency":5.42831E-4,"uri":"http://localhost:7101/api/v1/tags","path":"/api/v1/tags","remoteAddress":"unknown","result":"failure","status":"bad_request","httpMethod":"GET","httpStatus":405,"requestHeaders":[{"name":"Timeout-Access","value":"<function1>"},{"name":"Host","value":"localhost:7101"},{"name":"User-Agent","value":"curl/7.64.1"},{"name":"Accept","value":"*/*"}]}`

As you can see it's a GET request, and this works if I don't include memory.conf on startup

**Comment by brharrington** [comment]
Thanks for the report. It seems like it is something with the include that is part of the memory.conf now working depending on how the config path is specified. I was able to reproduce with:

```
java -jar atlas-1.6.4-standalone.jar memory.conf 
```

But, this works and should give you a workaround for now:

```
java -jar atlas-1.6.4-standalone.jar ./memory.conf 
```

Even so the error message is not ideal. I would have expected a 404.

**Comment by brsc2909** [comment]
I believe this is because the example links explicitly to the 1.5.x memory.conf. I was able to get this working by downloading from the master. 
```bash
curl -Lo memory.conf https://raw.githubusercontent.com/Netflix/atlas/master/conf/memory.conf
```
And then
```bash
java -jar atlas-1.6.4-standalone.jar ./memory.conf
```
