### ISSUE TITLE
plan for 1.5

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#115]
Goals for 1.5
- [x] binding for servo to atlas (probably in servo repo)
- [zero to cloud](https://github.com/brharrington/zerotocloud) example setup
  - [x] cloudwatch backend
  - [ ] cloudtrail backend
  - [ ] mirrored in-memory backend
  - [ ] all apps (eureka/edda/etc) publish to memory backend
  - [ ] regional aggregation cluster combining memory and cloudwatch backends
  - [ ] enable dynamic props (archaius) via dynamo for controlling atlas
  - [ ] system metric polling
- [x] experimental implementation of percentile db

Tentative date end of Q1.

**Comment by matschaffer** [comment]
Will cast my vote for mirrored in-memory back end. When chatting up atlas I find myself often saying "this thing is amazing but you lose the data when you restart" :)

If cloudwatch backend supported all the basic publish/query operations that'd probably be viable too. Basically anything to ensure metrics stick around after loss/restart.

**Comment by brharrington** [comment]
There are a few of those that are getting close to being merged in. I would be interested in learning a little more about how you are trying to use it and the ideal deployment model. For our typical setup we have 6+ clusters:

https://github.com/Netflix/atlas/wiki/Overview#resilience

But it was primarily setup that way to support the scale we needed for our largest deployments and there is quite a bit of configuration involved. Since we were the only ones operating it for a long time and we rarely do a clean install, ease of use for the operator wasn't a big concern. With the OSS setup we want to minimize the effort to get started where possible.

Also, one of the things I found when experimenting with the zero to cloud example is that it is extremely painful to operate without the automation we have internally. So I think at least some basic automation is needed to make that part viable and easier to test, but I haven't had time to look at it and I'm not really sure when or if the internal tools we're using would be an option externally.

**Comment by matschaffer** [comment]
So far my usage has taken two forms, both of which use https://github.com/stellar/docker-atlas for both and https://github.com/stellar/docker-stellar-core/blob/master/heka/stellar_core_metrics_filter.lua to pull data from the application.

1. One-off containers used to collect metric data during acceptance testing. Obviously no need for persistence there.

2. As a more-easily-explorable way to access app telemetry in production. For this I also use a single atlas instance, but the container generally sticks around and doesn't get restarted very often. 

For the second case, heka pulls data from the app, publishes it into both atlas & influx. Then I get dashboards from influx+grafana but still use atlas since it offers easier ways to explore the data and also easier sharing of pngs.

I use this atlas to power a basic alert system similar to the earlier one at Netflix (just alerts on any line > 0 that starts with "alert: ").

The data volume is still quite low so it's just one host running both influx and atlas and that's been fine. But some option around persisting data across reboots would make it easier to drop influx. Though I'd need to pick my atlas grafana plugin back up probably to provide something more approachable to folks not yet familiar with ASL.

**Comment by matschaffer** [comment]
As for deployment automation, I'm not too concerned with an answer to that as the places I'd look at deploying it probably already have some chef, puppet or ansible base to work from.

Would be curious to hear what in particular was painful to operate. I've found atlas very straight forward when compared with graphite or even influx.

Wonder if some of your pain might stem from how much better the netflix deployment tools are then most of what everyone else is doing.

**Comment by matschaffer** [comment]
@brharrington so it just dawned on me, when you roll out a new build of atlas do you just let the new instances sit for 4 hours (or whatever the first mirror retention is) before putting it in service?

The diagram also shows an arrow from M1->persistence. Is that somewhere in the current OSS distribution?

**Comment by brharrington** [comment]
> when you roll out a new build of atlas do you just let the new instances sit for 4 hours (or whatever the first mirror retention is) before putting it in service?

Yes. I put up an old presentation that shows a little more about how we run it:

http://netflix.github.io/atlas/atlas_overview.pdf#page=39

We will spin up a new instance and let it fill for the window for the short-term storage. This also lets us vet out the new version before we rely on it. When we're confident we'll terminate the old cluster.

> The diagram also shows an arrow from M1->persistence. Is that somewhere in the current OSS distribution?

There are a few parts to the persistence most aren't in the open repo yet, but enough to be generally functional will be for 1.5. 

* Copying to storage layer from the backend. We use an intermediate cluster that then proxies it to S3. This is mostly for historical reasons prior to S3 being the main storage, but we kept it because the proxy is then a simple stateless cluster that we can rev faster. The stateful deployments take longer. To simplify for the zero to cloud example I'm planning to have an option that will just write to an S3 bucket directly to reduce the number of moving parts. You could plug in some other storage if needed.
* Storage layer. We currently use S3 for this as it is convenient and we also do a lot of processing on the data using EMR for data correction across mirrors, computing rollups, usage reports, etc. For example, for longer historical we run a 4d and 2w cluster ([overview diagram](https://github.com/Netflix/atlas/wiki/Overview#resilience)). The main reason for having two is that we drop the node dimension and do some other rollups to reduce the cost for the longer 2w cluster ([metric counts by index](http://netflix.github.io/atlas/atlas_overview.pdf#page=50)). The rollups are computed in EMR. The EMR jobs and associated management tools are pretty tied into internal stuff right now so there are no immediate plans to open source that other than a high level goal to move as much as possible to the open repo over time.  
* Loading and serving from the storage layer. This should also be doable in 1.5, but there are a few caveats we have to figure out. In the EMR we also generate the output so we'll have an optimal number of files for the instance sharding we use on the historical. Not yet sure how that will work if we are directly using files produced from the mirrors to load.

**Comment by brharrington** [comment]
Thanks for the overview. We could also probably add some sort of simple file store that could back simple uses.

> Would be curious to hear what in particular was painful to operate.

Just a lot of manual steps and also I think some of it is the bootstrapping which was already done by others for the internal deployments. I've gotten used to just adding a small amount of config and checking in, then the deployment automation will deal with creating the images, asgs, elbs, dns names, security groups, etc.

@copperlight on our team is experimenting with [some options](https://github.com/copperlight/zerotocloud/tree/z2c-automation). Mainly what I want is an easy way to take a clean account and get a full stack running in a manner similar to how we run internally. This will give me a better way to vet stuff works and notice where we might be depending on internal assumptions. It should also make it easier for others get started or at least see a more concrete example.

**Comment by matschaffer** [comment]
Yeah, I miss a lot of that tooling on a daily basis. Brent's tooling especially :)

At least for testing atlas in a "clean" environment I suspect you could get by with just minimal scripts that set-up/tear-down the whole thing (clusters, EMR, etc).

Some sort of simple file storage would be a great start though. I was imagining something where memory is still where all the action happens, but there are periodic syncs to disk.

At least that way for small scale cases, I can recommend use of a single-instance atlas deployment with the file storage on a mounted EBS.

It wouldn't be HA, but it'd be easy to start and you could still repair a failure without losing the entire data set.

**Comment by matschaffer** [comment]
In other news, is atlas->cloudwatch planned for the OSS repo any time soon?

If it'd an avenue to do things like sum cloudwatch metrics across multiple dimensions I'd have a use for that as well.

**Comment by brharrington** [comment]
That should be straightforward, just need to find a bit of time to move it over. I'll try to get to it this week.

**Comment by matschaffer** [comment]
sweet! no big rush. I'll also need to polish my grafana->atlas plugin to make the best use of it

**Comment by pparth** [comment]
Version 1.5 anywhere near to be open-sourced? Or is this abandoned? Thanks.

**Comment by brharrington** [comment]
It's not abandoned, but I don't have a precise timeline right now. There are a lot of internal projects competing for time.

**Comment by pparth** [comment]
Anything new about this please? We see so many interesting things (dashboards, query builder, etc) in Netflix presentations, but we cannot get our hands on them!

**Comment by brharrington** [comment]
The current goal is to finish up 1.5 by end of April.

**Comment by pparth** [comment]
Any insight on whether you are going to open source the resilience-related features?

**Comment by brharrington** [comment]
I would like to, it is mostly a question of time. There may be some help coming on that front, but not sure yet.
