### ISSUE TITLE
no labels shown on y-axis for certain values

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#119]
http://localhost:7101/api/v1/graph?q=2027

![missing-label](https://cloud.githubusercontent.com/assets/1289028/6323764/b1d03676-bae4-11e4-9992-326c8dffd035.png)

For large enough values if the line is flat enough it can fall between major tick marks and no labels will be shown on the y-axis.

**Comment by copperlight** [comment]
The workaround is to set the lower bound to zero.

**Comment by brharrington** [comment]
![2027](https://cloud.githubusercontent.com/assets/1289028/7765320/8910a7c6-0011-11e5-8c8c-327512c48e1f.png)
