### ISSUE TITLE
Q: Atlas vs Prometheus 

### ISSUE THREAD

**Issue by MacNale** [Netflix/atlas#1408]
Hello Community,

I was looking for a metric store to store high cardinality metric data collected by existing agents. I came across Atlas and also familiar with Prometheus. Are there any advantages of choosing Atlas over Prometheus?  Is Apache Druid being used in the stack somewhere beside Atlas?

Thanks,
Mac

**Comment by brharrington** [comment]
Both Atlas and Prometheus are time series data bases. Note, that neither is really optimized for high cardinality dimension values, so if that is your use-case, then you would probably want to look elsewhere. For example from the Prometheus docs:

https://prometheus.io/docs/practices/naming/

> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

That would apply to Atlas as well. 

More generally, Atlas is mostly geared towards the internal use-cases at Netflix and is open sourced primarily just for sharing information. There are a few external users, but you would need to be much more self sufficient, and it would probably take more work to get started. There is a blog post from a company called Outlyer (no longer around) that discussed their usage of Atlas:

https://medium.com/dataseries/why-not-to-build-a-time-series-database-e1e63a535357

It is important to note there that Atlas was an internal component as part of a larger system they were building. That is similar to the internal setup at Netflix where there is also a large internal ecosystem of tools built around it that are mostly not available externally. For most users just looking for a quick monitoring setup with associated open tooling, the Prometheus ecosystem is probably going to be a better choice.

As to Druid, Netflix also uses Druid internally for some use-cases. There are also some internal uses where we have the Atlas query layer fronting Druid backends. Our uses for that are mostly some higher cardinality dimension data where we are looking for different cost, performance, and reliability tradeoffs than what we expect from the standard Atlas storage.
