### ISSUE TITLE
any chance version 1.6.7 will be released ?

### ISSUE THREAD

**Issue by michielgkalkman** [Netflix/atlas#1473]
Hi,

Thanks for Atlas!

We would like to use a newer version than what is available now, mostly because version 1.6.6 and before use an unacceptable version of log4j.

Is there any chance that version 1.6.7 will be released anytime soon?

Thanks in advance!

**Comment by brharrington** [comment]
[1.6.7](https://github.com/Netflix/atlas/releases/tag/v1.6.7) has been released.

**Comment by michielgkalkman** [comment]
Awesome, thanks!
