### ISSUE TITLE
publishing

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#15]
This has several parts:
- Bindings for servo (internal atlas-plugin lib)
- Figure out a story for metrics (independent or leverage plugin for things like local alerting)
- Configuration setup for running the clusters needs to be cleaned up a bit and documented.

**Comment by krutsko** [comment]
Do you have any new on that?

Maybe somebody has a successful story with publishing Timers to Atlas?

Just in case, filed a question under Spectator project:
https://github.com/Netflix/spectator/issues/239

**Comment by pparth** [comment]
+1

**Comment by matschaffer** [comment]
I've been using hekad to scrape http and publish to atlas over http without
any trouble.

https://github.com/stellar/docker-stellar-core/blob/master/heka/stellar_core_metrics_filter.lua
is
the filter.

It's a little app specific. I have a mostly-functional statsd version I can
post later tonight.

On Thursday, 5 November 2015, Panos Partheniadis <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Netflix/atlas/issues/15#issuecomment-154008183>.
>


-- 

-Mat

matschaffer.com

**Comment by matschaffer** [comment]
Here's a heka filter for use with the statsd input - https://gist.github.com/matschaffer/877c42dd1a3443a0e2a4

It works but doesn't separate out tags. Was thinking of setting it up so it would allow you to have dotted pairs like `request=foo.controller=bar.some.metric.name` where it would plug out the things that look like key/value as tags then set the name value to the remainder.

**Comment by brharrington** [comment]
Thanks @matschaffer !  For the java uses you can also look at:

https://github.com/Netflix/servo/tree/master/servo-atlas

I still need to do quite a bit of work on documentation and getting a few more internal components refactored and merged into the open repo. I'm pretty strapped for time for the next month though.

**Comment by krutsko** [comment]
Thanks @matschaffer and @brharrington

**Comment by brharrington** [comment]
Simple example publishing to itself:

https://github.com/Netflix-Skunkworks/iep-apps/tree/master/iep-atlas

There is also a script showing a basic example:

https://github.com/Netflix/atlas/blob/master/scripts/publish-test.sh

**Comment by pparth** [comment]
@matschaffer  I know this is an old issue but have you managed to publish metrics to Atlas from Statsd? Do you have any code to share?
