### ISSUE TITLE
Have MemoryBlockStore use atlas.webapi.publish.max-age

### ISSUE THREAD

**Issue by matschaffer** [Netflix/atlas#175]
Noticed while attempting to do 1s resolution (on a very small data set) that MemoryBlockStore implements its own "data too old" check: https://github.com/Netflix/atlas/blob/master/atlas-core/src/main/scala/com/netflix/atlas/core/db/BlockStore.scala#L193

For now I can switch to 5s resolution but not sure 1s is possible across hosts since just a little clock skew could cause the data to be rejected.

If possible it'd be good to have this honor the max-age setting from publish.

Also having it include the timestamps in the message similar to https://github.com/Netflix/atlas/blob/master/atlas-webapi/src/main/scala/com/netflix/atlas/webapi/PublishApi.scala#L82 would be nice to make it clearer just how far skewed things are.

**Comment by brharrington** [comment]
The checks serve different purposes. The one in the block store is showing that is trying to write to a block that has already been completed. Usually that happens if data arrives out of order for a given time series.

What is the max-age you are using with a 1s step?

**Comment by matschaffer** [comment]
Ah... perhaps I need to tune out the rebuild frequency then.

Here's the conf I was trying: https://github.com/stellar/docker-atlas/blob/master/conf/atlas.1s.conf#L31

The use case is that we have a single docker container that exists for the purpose of collecting metrics during integration testing.

So I'm happy to have metrics show up fairly late since we won't be using them until long after the test is complete.

**Comment by matschaffer** [comment]
The case I was seeing with this config (and a 1s poller publishing data) was that everything was getting rejected. Here's a pcap of what went between the host & atlas incase it helps: https://dl.dropboxusercontent.com/u/54805/atlas-traffic.pcap.zip

**Comment by brharrington** [comment]
I was able to reproduce on v1.4.x branch, but not master. I'll try to isolate the change tomorrow.

**Comment by matschaffer** [comment]
Thanks! "use master" would likely be a fine solution for this as well.

**Comment by brharrington** [comment]
Problem was that the max-age setting was getting ignored, it came in as part of the validation rules added to master. That is now backported to 1.4.x branch.

**Comment by matschaffer** [comment]
Thanks for back porting! Also looking forward to 1.5 :)
