### ISSUE TITLE
Feature request: KairosDB backend for Atlas

### ISSUE THREAD

**Issue by lcoulet** [Netflix/atlas#20]
It looks to me that Atlas with kairosDB as a datastore backend would be a winning team. KairosDB has most of OpenTSDB features while being more flexible under many aspects.
Moreover, netflix is already known as a large contributor to Cassandra world, and Cassandra is by design the primary datastore for the KairosDB time series database with a very efficient design for time series data.

**Comment by gnydick** [comment]
Just wanted to add my $0.02. Given this thread is a couple years old, I've been using OpenTSDB for a couple years and it's been fantastic and very high performance under high volume. Happy to talk to anyone interested.

**Comment by brharrington** [comment]
We'll revisit in the future, but for now there are no current plans and we do not have the bandwidth to work on it. Closing the issue to help with some of our tracking.
