### ISSUE TITLE
More accurate dead letter count

### ISSUE THREAD

**Issue by drewhk** [Netflix/atlas#235]
The line here in UnboundedMeteredMailbox (https://github.com/Netflix/atlas/blob/master/atlas-akka/src/main/scala/com/netflix/atlas/akka/UnboundedMeteredMailbox.scala#L64)

     def cleanUp(owner: ActorRef, deadLetters: MessageQueue): Unit = {
        deadLettersCounter.increment(queue.size)
        queue.clear()
      }

attempts to count dead letters, but it will only record those that were already in the mailbox when the actor stops. Dead letters may arrive later than this point because either their enqueueing was in race with the shutdown, or because some actors are still sending messages to the reference after termination. In fact this latter is usually more important to record, since if an actor does not properly watch another, then the counter will increase monotonically, which the current implementation does not track (at leas as far as I see).

You can tap directly onto the dead letters as described here, maybe that is a better approach:

http://doc.akka.io/docs/akka/2.4.0/scala/event-bus.html#Dead_Letters

**Comment by brharrington** [comment]
Thanks for the report. I'll try out your suggestions when I get a chance.

**Comment by drewhk** [comment]
thanks, solution looks good. Happy Hakking :)
