### ISSUE TITLE
Question: Atlas Http Api

### ISSUE THREAD

**Issue by utkarshcmu** [Netflix/atlas#284]
Hello @brharrington ,

I have a question about Atlas Http API. Is there an API which support the following pattern or similar?

Request -> Takes metric name, tags, start and end time.
Response -> Returns metric name, tags, datapoints as a JSON object

**Comment by brharrington** [comment]
You can get json output from the graph api, see:

https://github.com/Netflix/atlas/wiki/Graph#output-format
https://github.com/Netflix/atlas/wiki/Output-Formats#stdjson

The name, tags, and aggregation to use would be part of the query expression.

**Comment by utkarshcmu** [comment]
@brharrington Thanks for the resources. I am able to setup a test atlas instance.
