### ISSUE TITLE
Grafana plugin support

### ISSUE THREAD

**Issue by utkarshcmu** [Netflix/atlas#289]
It would be awesome if we can visualize graphs in Grafana with Atlas as a backend.

https://github.com/grafana/grafana-plugins/issues/64

**Comment by brharrington** [comment]
@matschaffer did some work on that a while back:

https://github.com/grafana/grafana-plugins/tree/master/datasources/atlas

Not sure of the current status. When I get some time I'll try it out and add some docs to the wiki for it.

**Comment by utkarshcmu** [comment]
Thanks. Hopefully, I should be able to firt soon.

**Comment by ivanarkhipov** [comment]
There is pull request for Atlas datasource plugin for Grafana 2.6. https://github.com/grafana/grafana-plugins/pull/74

**Comment by brharrington** [comment]
https://github.com/upwork/grafana-atlas-datasource

**Comment by utkarshcmu** [comment]
We can close this issue then. As we have a the above link to plugin. Thanks @brharrington @ivanarkhipov

**Comment by hello-earth-gh** [comment]
the above links mostly give 404 now, this one seems to work - as a plugin in Grafana 8 too... https://github.com/briangann/grafana3-atlas-datasource

**Comment by manolama** [comment]
@hello-earth-gh Looks like the old plugins were moved to https://github.com/grafana/attic/tree/master.

**Comment by llamafilm** [comment]
Is anyone still actively using or maintaining this plugin?  It's not listed at https://grafana.com/grafana/plugins/.
I'd like to use this, but that "attic" shows 2 versions `atlas` and `atlas-2.6` and I'm not sure which one to use.

**Comment by llamafilm** [comment]
I'm only a beginner Grafana user, but I gave this a try and it seems like this plugin is defunct.  The first one doesn't load at all.  The 2.6 version fails to load (in Grafana 10.1) with this error:

> "Skipping plugin loading as its plugin.json could not be read" path=/var/lib/grafana/plugins/atlas/plugin.json err="did not find valid type or id properties in plugin.json"

The structure of `plugin.json` looks quite different than the [docs](https://grafana.com/docs/grafana/v10.0/developers/plugins/metadata/), so I guess it was written for a much older version.

**Comment by manolama** [comment]
@llamafilm That attic plugin would be for a very old version of Grafana and incompatible with 10.x. We don't use Grafana with Atlas internally so it's unlikely that there is a maintainer around to update it for newer Grafana releases.
