### ISSUE TITLE
It's not clear to me how to get data in

### ISSUE THREAD

**Issue by nicferrier** [Netflix/atlas#34]
I presume data collection is orthogonal to atlas, but atlas does seem to be a storage engine. The get going examples are cool because they deliver data that you can play with... but that doesn't answer my question.

Any clue on how to get data in?

**Comment by ppadala** [comment]
Would love to try this, when you have information on how to get data into Atlas. I see that https://github.com/Netflix/atlas/issues/15 also talks about plugins for collecting various kinds of metrics. It will be good to know how to set that up as well.

**Comment by brharrington** [comment]
Simple example shown in wiki:

https://github.com/Netflix/atlas/wiki/Getting-Started#running-demo-with-memory-storage

There is some ongoing discussion about the best place to put the client lib that has the bindings for servo and how much this depends on internal assumptions. As that gets ironed out we'll update #15.
