### ISSUE TITLE
Meaning of rebuild-frequency

### ISSUE THREAD

**Issue by drax68** [Netflix/atlas#363]
Hi, could you provide meaning of rebuild-frequency?
Is there any drawbacks of increasing it to 30s/60s/120s?
Will it affect overall atlas memory/cpu consumtion and overall perfomance?

**Comment by brharrington** [comment]
There is some overhead in rebuilding both in terms of temporary memory overhead and cpu. How much depends a bit on the data characteristics. The main benefit of rebuilding frequently is that new data will not be searchable until it has been indexed. We typically set it roughly the same value as the data step size.

**Comment by drax68** [comment]
Thank you for explanation, it's clear now.
