### ISSUE TITLE
Alternative to Graph API

### ISSUE THREAD

**Issue by sourav82** [Netflix/atlas#366]
I was experimenting with standalone version of Atlas. 
I was wondering if there are any HTTP APIs (other than graph API) to query aggregated metrics information from Atlas. I wanted to query Atlas from some Python application for aggregated metrics. Is there any API available to query aggregated metrics (say, sum every one hour) from Python?

**Comment by pparth** [comment]
You can use alternative output formats: https://github.com/Netflix/atlas/wiki/Output-Formats

**Comment by sourav82** [comment]
@pparth  Ahh.. Thanks! Missed this information.
