### ISSUE TITLE
Rule based alert definition and actions

### ISSUE THREAD

**Issue by sourav82** [Netflix/atlas#367]
Is there any way (possibly, UI) we can define alert? Any documentation on creating alert and custom notification will be helpful.  More specifically, in the documentation https://github.com/Netflix/atlas/blob/master/atlas-wiki/src/main/resources/Alerting-Philosophy.md#keep-it-simple, how to create the alert `CPU Usage > 80% for at least 5 minutes`?

**Comment by sourav82** [comment]
More specifically, in the documentation https://github.com/Netflix/atlas/blob/master/atlas-wiki/src/main/resources/Alerting-Philosophy.md#keep-it-simple, how to create the alert `CPU Usage > 80% for at least 5 minutes`?

**Comment by brharrington** [comment]
There is a separate internal system that executes alerting rules on top of the Atlas backends. Unfortunately the UIs and some of the other systems built on top of Atlas are not currently open source. @SomeKittens and @fangji are the main owners for alerts and may be able to provide more context.

In general simple threshold alerts get defined as an expression where a 0 indicates everything is ok and a 1 (or really a non-zero value) means the alert triggered. I included an example below using the demo dataset.

**Input Line**

http://localhost:7101/api/v1/graph?q=name,ssCpuUser,:eq,:max&e=2012-01-01T06:00&s=e-3h&tz=UTC&l=0

![input](https://cloud.githubusercontent.com/assets/1289028/15901122/e2e2671c-2d56-11e6-9d1b-999a4e813d91.png)

**> 80%**

http://localhost:7101/api/v1/graph?q=name,ssCpuUser,:eq,:max,80,:gt&e=2012-01-01T06:00&s=e-3h&tz=UTC&l=0

![80gt](https://cloud.githubusercontent.com/assets/1289028/15901246/57c00a80-2d57-11e6-88d6-705fac2d0f1f.png)

**Num Occurrences**

We do num occurrences using the [:rolling-count](https://github.com/netflix/atlas/wiki/stateful-rolling%E2%80%90count) operator.

http://localhost:7101/api/v1/graph?q=name,ssCpuUser,:eq,:max,80,:gt,6,:rolling-count&e=2012-01-01T06:00&s=e-3h&tz=UTC&l=0

![num-occurs](https://cloud.githubusercontent.com/assets/1289028/15901409/03fed498-2d58-11e6-99af-c6b7a20a7a92.png)

**For at least 5 minutes**

http://localhost:7101/api/v1/graph?q=name,ssCpuUser,:eq,:max,80,:gt,6,:rolling-count,4.9,:gt&e=2012-01-01T06:00&s=e-3h&tz=UTC&l=0

![atleast](https://cloud.githubusercontent.com/assets/1289028/15901388/f3f61d4a-2d57-11e6-9040-d84dfd0a6fdf.png)

This would be the actual signal line that would be used for the alerting system.

**Visualization**

The signal line is used to tell whether something should fire. To make it easier for human consumption we usually do a simple rewrite on the signal expression to get a visualization that is included with the notification messages and is easier to follow for a person. The visualization would look like:

http://localhost:7101/api/v1/graph?q=name,ssCpuUser,:eq,:max,:dup,80,:gt,6,:rolling-count,4.9,:gt,triggered,:legend,40,:alpha,:vspan,80,threshold,:legend&e=2012-01-01T06:00&s=e-3h&tz=UTC&l=0

![alert-viz](https://cloud.githubusercontent.com/assets/1289028/15901584/af09d1e4-2d58-11e6-9540-75881b2d5d28.png)

**Comment by sourav82** [comment]
Thanks a lot @brharrington. This is really helpful.

**Comment by matschaffer** [comment]
I did a really simple system last year that would fire an email off for a
graph that had any legend entry with "alert: ", then had a big yaml file of
atlas queries and descriptive text.

Did the trick pretty well.

I'd share, but I did it on hekad which I wouldn't really recommend using at
this point. Should be able to do something pretty similar with cron and a
script.


-Mat

matschaffer.com

**Comment by brharrington** [comment]
The check and trigger loop is pretty simple. For us most of the complexity is around suppression and actions. In particular, being able to manage the volume of notifications is critical or users will start ignoring alerts.
