### ISSUE TITLE
Tags API Data Disappears

### ISSUE THREAD

**Issue by makaveli0129** [Netflix/atlas#374]
When i run a publish i have the data and i see the tags immediately when i query the /api/v1/tags. The weird this is that after the metadata rebuild the tag disappears and is no longer showing in the call to /api/v1/tags. 

I can replicate this issue if you use a start time of now() in my case (1465416849358). The tags stick around. If you use a start time of 1465326029000. The tags disappear after rebuild. Is there some time constraint on listing of the tags? Below is memory.conf for testing purposes.......

```
atlas {

  core {
    model {
      step = 1 minute
    }

    db {
      class = "com.netflix.atlas.core.db.MemoryDatabase"
      //class = "com.netflix.atlas.core.db.StaticDatabase"

      // How often to rebuild the index for the memory database
      rebuild-frequency = 8s

      // 1h with 1m step
      block-size = 60

      // 6h of data overall
      num-blocks = 6
    }
  }

  webapi {
    main {
      port = 7101
    }

    graph {
      // Change default start time on graph to smaller range more typical for testing
      start-time = e-30m
    }

  publish {

      // Max age for a datapoint. By default it is one step interval. If the timestamps are
      // normalized locally on the client 2 times the step is likely more appropriate.s
      max-age =  600000000
    }
  }

  akka {
    api-endpoints = ${?atlas.akka.api-endpoints} [
      "com.netflix.atlas.webapi.PublishApi"
    ]
  }
}
```

**Comment by brharrington** [comment]
Looking at the times:

```
1465416849358 => Wed, 08 Jun 2016 20:14:09 GMT
1465326029000 => Tue, 07 Jun 2016 19:00:29 GMT
```

Assuming `now`, is the first time, the second time would be too old and should get rotated out. From the sample config:

```
      // 1h with 1m step
      block-size = 60

      // 6h of data overall
      num-blocks = 6
```

So it should only keep up to the last 6h of data. In practice it will be 5 to 6 hours for a time series that is regularly reported.

**Comment by makaveli0129** [comment]
yea i'm an idiot........it was a long yesterday sorry about this......
