### ISSUE TITLE
Include aggregation strategy in metadata format (v2.json)

### ISSUE THREAD

**Issue by tregoning** [Netflix/atlas#381]
It would be useful to include the effective [aggregation](https://github.com/Netflix/atlas/wiki/Stack-Language#aggregation) function(s) for a given chart/query when using the [metadata format](https://github.com/Netflix/atlas/pull/298)

That way, when a dynamic chart is resized, the correct aggregation function can be used.

**Comment by brharrington** [comment]
Clarifications from in-person conversation:

* The concern is mostly the [consolidation function](https://github.com/Netflix/atlas/wiki/Concepts#consolidation-function) which is typically chosen automatically based on the aggregation function used for a data query. 
* The main goal would be to allow a dynamic chart to resize and perform accurate consolidation without doing another request to the backend.
* For most expressions a line on the graph would have a single consolidation function used for the underlying data to create that line. However, for completeness it is possible to create a line that uses a mix, e.g., `name,sps,:eq,:max,name,sps,:eq,:sum,:add`. 
* We should be able to emit the consolidation behavior if possible and if it cannot be reliably determined just indicate another request would be needed to get precise behavior.
