### ISSUE TITLE
comparison violates contract error

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#405]
In some cases when using legend sorting we get an error like:

```
IllegalArgumentException: Comparison method violates its general contract!
```

Known example is using `min,:sort,desc,:order`. The default order works fine. Max and average work with either order.

**Comment by svachalek** [comment]
It possibly depends on the data being sorted as well. It was reported to me last night with a max,:sort query but I didn't reproduce the error until I replaced it with :min.
