### ISSUE TITLE
[Question] Eureka server integration

### ISSUE THREAD

**Issue by lostvicking** [Netflix/atlas#443]
Hi all,

I'd like to get Atlas to register with my Eureka server. It looks like I can't use the standalone jar, however, I'm not sure what I can do in order to enable Atlas as a Eureka client. Can anyone point me in the right direction please?

Regards
Victor

**Comment by brharrington** [comment]
Internally we do it using [iep-module-eureka](https://github.com/Netflix/iep/tree/master/iep-module-eureka). I'll try to put up a simple example later today.

**Comment by brharrington** [comment]
https://github.com/Netflix-Skunkworks/iep-apps/tree/master/iep-atlas
