### ISSUE TITLE
1.5.0: port override doesn't work any more

### ISSUE THREAD

**Issue by andysworkshop** [Netflix/atlas#451]
Changing the port number in `memory.conf` used to work. It doesn't any more. The port stays at 7101 regardless of what you set.

**Comment by andysworkshop** [comment]
It seems that `webapi.port` is no longer used (should it be removed from the source now?). The replacement is `atlas.akka.port`.

**Comment by brharrington** [comment]
Thanks for the report, I'll get that fixed.
