### ISSUE TITLE
Question: Why does Atlas push data be to be "on the minute" and how close to the next minute?

### ISSUE THREAD

**Issue by briangann** [Netflix/atlas#477]
Something I noticed - and this is likely intentional - when you ingest data into Atlas then read it back out, the timestamp is always "on the minute" vs the actual timestamp of the ingested data.

If I ingest data at time 12:00:01, it shows up as 12:00:00
If I ingest data at time 12:00:58, it shows up as 12:01:00

To better illustrate this: [https://bkgann.files.wordpress.com/2016/12/influx_predixts_atlas.jpg?w=840](url)

I'm writing the same data to InfluxDB and Atlas, you can see the "actual" timestamps of the data in InfluxDB, and the "pushed" timestamps of the data in Atlas.

In the last 5 minutes of that graph, I set the step size for InfluxDB to be 1 minute, the overall graph looks similar, but the timestamp lands where the the actual datapoint occurred.

I'm curious how Atlas is deciding to push data forward to the "next minute" - I would have expected all values within a minute range to land in the same minute - but from the graphs it looks like data close to the next minute is pushed forward.

Meaning ingesting a datapoint at 12:00:58 queries back as a datapoint at 12:01:00, vs 12:00:00 (which you can see in the comparison graph)

**Comment by brharrington** [comment]
Somehow I overlooked this question. There is some explanation of this in the docs:

https://github.com/Netflix/atlas/wiki/Concepts#data-point

Atlas follows a similar model to [RRD] and originally replaced a solution that was based on RRDtool internally at Netflix. This blog post discusses some of the tradeoffs between whisper which sounds like it would be similar to Influx's model and RRD which is very similar to Atlas's model:

https://grisha.org/blog/2015/05/04/recording-time-series/

[RRD]: https://oss.oetiker.ch/rrdtool/doc/rrdcreate.en.html
