### ISSUE TITLE
add internal fetch api

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#547]
Internal fetch api should be added to open source repo. Target is end of April.

/cc @skandragon

**Comment by brharrington** [comment]
Initial port done, will follow up on other issues separately.

**Comment by pparth** [comment]
Can we have a clue about what is the fetch API? Is it related to the data stream feature discussed elsewhere?

**Comment by brharrington** [comment]
Fetch API has been around for quite a while internally and was moved over because we are trying to gradually reduce the amount of internal add-ons. In general this means we are either going to transition it to the public repo or phase it out. 

One of the problems we have with the graph API is that most of the output formats require us to have all the data at one time to generate the response. This is pretty limiting for some use-cases where we wanted to be able to support requests with larger responses. The fetch API is not for a continuously running stream, but is meant to allow the server to incrementally process a request and emit data as it is ready rather than have to hold on to all of it to generate the final response. So the response is setup in such a way that it can partition the data as needed either across time or across the set of time series to limit the amount of resources needed on the server to process the request. Though the request does not have a strict latency bound.

SSE was used for the response format because there were some browser use-cases and the [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) libraries were the easiest way to process results incrementally from the browser without using web sockets. At the time it was created there were a number of road blocks to using web sockets and we let others pay the pioneer tax. It is something we'll probably revisit when we get the time.

**Comment by pparth** [comment]
thanks for the info.
