### ISSUE TITLE
add support for diagnostic messages over stream

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#575]
When doing the streaming evaluation we should support some diagnostic messages to make it easier for users to debug. Examples:

* Failed or partial connectivity to LWC
* Invalid URL provided by the user

/cc @neerajrj

**Comment by neerajrj** [comment]
Sending a message on register / deregister expression would be great as well. Especially since it takes a bit of time for results to start flowing out acknowledging the expression was registered successfully would be useful
