### ISSUE TITLE
should NaN be considered > or < other numbers when sorting?

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#586]
Consider the example:

```
/api/v1/graph?q=NaN,1,2,4,8&sort=avg&order=desc
```

Currently this will result in:

![sort-nan](https://cloud.githubusercontent.com/assets/1289028/26119859/9cc4cefc-3a23-11e7-8b4e-0641b3ddb46a.png)

When sorting by stats rather than the legend text, descending order is probably the most common. Should `NaN` values when present get treated as less than others so they are at the end? This might also generally agree with the behavior on some operators, e.g. `:add`, where `NaN` is treated as 0. Though in this case `NaN` would also be less than negative numbers, but those tend to be infrequently used in practice.

/cc @svachalek @jameskojo

**Comment by brharrington** [comment]
Suggestion from @vfilanovsky , always put `NaN` at the end regardless of order.

**Comment by svachalek** [comment]
I think when sorting by a statistic the goal is to pull the most interesting lines to the top, while lines with no data are almost certainly the least interesting. Therefore always sorting them to the bottom seems like a good idea.
