### ISSUE TITLE
how to model conceptual types?

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#597]
The goal of this proposal is to make it easier for a UI or other tooling built on top of Atlas to reliably detect and work with types.

## Background

Internally Atlas really only has two core types rates and gauges that are associated with tags. Those types impact the [normalization](https://github.com/Netflix/atlas/wiki/Concepts#normalization) behavior that takes effect for that data, but for the most part the end user viewing the data does not need to care about this distinction. The end user mostly cares about the conceptual type like [counter](http://netflix.github.io/spectator/en/latest/intro/counter/), [timer](http://netflix.github.io/spectator/en/latest/intro/timer/), etc from a reporting library. 

The backend itself is unaware of these conceptual types and that is desirable as we want to keep the backend simple and general. Early on this was also useful as we were learning more about what types were useful and how to encode them in a reasonable way. However, it is important for usability for tools to be able to reason about some of these types so they can be presented to the user effectively. There are ways to partially do this now, but it is a bit cumbersome and has many corner cases.

The conceptual types map to one or more time series and use tags to differentiate between various parts. The most common example of this is the [timer](http://netflix.github.io/spectator/en/latest/intro/timer/) type that in the basic form sends four time series per timer differentiated by the statistic:

* `totalTime`: counter incremented by the amount recorded, unit of `seconds/second`
* `count`: counter incremented for each recorded value, unit of `events recorded/second`
* `totalOfSquares`: counter incremented by the square of the recorded amounts, unit of `seconds^2/second`
* `max`: gauge showing the maximum recorded value for the interval, unit of seconds.

Timers can be extended, for example [bucket timer](http://netflix.github.io/spectator/en/latest/javadoc/spectator-api/com/netflix/spectator/api/histogram/BucketTimer.html) and [percentile timer](http://netflix.github.io/spectator/en/latest/javadoc/spectator-api/com/netflix/spectator/api/histogram/PercentileTimer.html) which provide additional tags. The bucket timer will add a bucket tag to all stats of the timer. The percentile timer will create a separate set of counters with the same base id, but no statistic tag and a percentile tag that is used to estimate the percentile value.

Raw counters and gauges are just reported with the user tags.

## Goals

* Simple way to select or restrict to time series of a given type. This is not currently doable for all conceptual types supported by spectator.
* Simple way to determine the type or set of types that match a given query. This can partially be done, in particular for timers and distribution summaries.

## Proposal 1

Use the statistic tag to indicate the type. This has the benefit that it is already in place for timers and distribution summaries. Spectator would always add a statistic tag to all time series. The statistic tag could then be used to satisfy the two goals.

### Restrict to Type

To query for time series of a given type the restriction queries below can be used:

| Type                          | Query to restrict                                   |
|-------------------------------|-----------------------------------------------------|
| Counter                       | statistic,count,:eq                                 |
| Gauge                         | statistic,gauge,:eq                                 |
| DistributionSummary           | statistic,totalAmount,:eq                           |
| Timer                         | statistic,totalTime,:eq                             |
| LongTaskTimer                 | statistic,duration,:eq OR statistic,activeTasks,:eq |
| IntervalCounter               | statistic,interval,;eq                              |
| BucketCounter                 | statistic,count,:eq,bucket,:has,:and                |
| BucketDistributionSummary     | statistic,totalAmount,:eq,bucket,:has,:and          |
| BucketTimer                   | statistic,totalTime,:eq,bucket,:has,:and            |
| PercentileDistributionSummary | statistic,percentile,:eq,percentile,D,:re,:and      |
| PercentileTimer               | statisitc,percentile,:eq,percentile,T,:re,:and      |

Note, that some queries can mix types and this is considered desirable. For example, all timers have a counter that can be used to see the number of recorded events. This means a timer measuring request latency could also be used to see the RPS by restricting to the count statistic. With this proposal if selecting the set of counters the counter aspects of timers will also show up. Similarly, supersets of timers like percentile timers and bucket timer would show up when querying for a basic timer. However fundamentally different timers like [long task timer](http://netflix.github.io/spectator/en/latest/intro/timer/) would not.

### Determine Types for Query

To determine the set of types that are present for a given query, we can simply project the statistic. That is:

```
/api/v1/tags/statistic?q=...
```
The table below shows the types present based on values in the response:

| Statistic                 | Type                                  |
|---------------------------|---------------------------------------|
| count                     | Counter                               |
| gauge                     | Gauge                                 |
| totalAmount               | DistributionSummary                   |
| totalTime                 | Timer                                 |
| totalOfSquares                 | Timer/DistributionSummary                                |
| activeTasks               | LongTaskTimer                         |
| duration                  | LongTaskTimer                         |
| interval                  | IntervalCounter                       |
| percentile                | Percentile{Timer/DistributionSummary} |

There are a number of gaps/questions here:

* Bucket types cannot be distinguished because it is an additional tag that modifies all the parts of the underlying type. Since they are designed to be used by simply grouping by the `bucket` tag that is not considered a big shortcoming. The bucket can be considered a dimensional aspect of the type rather than a namespacing aspect.
* The percentile type would need the presence of `totalTime` or `totalAmount` to figure understand what type it is extending. Alternatively we could make the statistic something like `percentileTimer` and `percentileDistSummary`.
* Should `duration` and `interval` be merged? Though it has been used for a while in various forms by users, the IntervalCounter is a new pattern addition to spectator, so `interval` could change. From a user perspective they are used in the same way similar to the counter aspect of a timer. The only real benefit of keeping them separate is it gives a way to identify conceptual type the user was working with was the IntervalCounter.

### Compatibility Issues

Most are fairly minor, statistic has been used for a long time and not recommended for use by users. We would likely need to lock it down a bit so it is only used by the tools and longer term we could update validation to restrict to known values. We would also likely need to move statistic to a reserved tag so it does not count toward the user tag limit.

Servo is messy, in particular, with respect to timer units. This means that if servo data is being sent in, then you cannot rely on the timer units being seconds. One could counter that by excluding legacy data from servo by looking for the `type` tag that it adds which is close to the Atlas dstype concept than it is to the conceptual types. However, this would require a change to servo to drop the `type` tag for things that conform to the spec here.

### Extensions

Future extensions would either need to use a set of the existing stats or use a new statistic value that gets setup. How this is done would likely depend on whether the set of operations available depends on the type. For example, the bucket timer can be used with a simple group by, there are no additional operators needed. The percentile timer needs the `:percentile` operator to compute the estimate so it is a separate statistic. Similarly things like `totalOfSquares` advertise a capability for a timer in that if you have `count`, `totalTime`, and `totalOfSquares`, then  `:dist-stddev` can be used to compute the standard deviation. You could still have a basic timer with just `count` and `totalTime` but you could only compute the average.

As an example, consider adding support for [HyperLogLog](http://algo.inria.fr/flajolet/Publications/FlFuGaMe07.pdf). The registers would need to get encoded using a tag value similar to how we do percentiles. Since we would need a specific operator to compute the final estimate, this would need to be a new statistic value.

## Proposal 2

Does anyone have a better proposal?

/cc @dmuino @copperlight @svachalek @tregoning @nathfisher

**Comment by pparth** [comment]
Regardless the decision made out of this, i really think @brharrington  that most of this article, especially the Background and the Proposal 1 sections, should find its way into the documentation. We have been struggling for months about how to interpret this discrepancy between how the server and the latest version of the Spectator client realise metric types. This article provides valuable insight about how you think about metric types and also clears things up for users. I really do not understand why you are trying to keep the Statistic tag a secret from users. I think that, it should be a first class citizen, if only for the exact reason to help us understand more about the metric types.

**Comment by brharrington** [comment]
@pparth thanks for the feedback. Will try to get some of this incorporated back into the docs.

> I really do not understand why you are trying to keep the Statistic tag a secret from users.

We're not trying to keep it a secret. I'm guessing that impression comes from "Most are fairly minor, statistic has been used for a long time and not recommended for use by users". The wording on that now that I re-read it is misleading. When creating metrics it is recommended that users do not use the statistic tag key because it is used internally for modeling the types for timers and distribution summaries (and possibly on everything depending on the outcome here). When doing changes like this we have to be careful about how it will change or break existing use-cases. For example, if a user used a tag key of statistic for something else and then it gets overwritten.

 For queries it is expected to be used and is quite heavily now by the internal UI. This is basically looking at taking something the team supporting our internal UI are already doing and making it more robust and well supported from the client all the way down.

**Comment by pparth** [comment]
Ok, got it now.

**Comment by pparth** [comment]
@brharrington  The Counter and Gauge implementation in the Spectator Atlas Registry, do not support any statistic Tag: 
https://github.com/Netflix/spectator/blob/master/spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasCounter.java
https://github.com/Netflix/spectator/blob/master/spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasGauge.java

DistributionSummary and Timer seem to be ok.

However, the BucketXXX and PercentileXXX are also not properly defined in the Spectator Atlas Registry.

**Comment by brharrington** [comment]
Correct. If the proposal is agreed to, then we would add those in.

**Comment by pparth** [comment]
I may understand the Counter and Gauge but i do not see the correlation with the BucketXXX and PercentileXXX ones. They are supposed to derive from the relevant DistributionSummary and Timer ones, where the proper statistic tags are already there. So, they now have the extra bucket tag and do not have the underlying ones, which is very confusing...

**Comment by brharrington** [comment]
The Bucket and Percentile variants are extensions to existing types. For this reply I'll just focus on the timer. 

**BucketTimer**

BucketTimer basically just maintains one timer per bucket. So when a value is recorded it will get mapped to a bucket and then that time will get updated. So for a given baseId we end up with:

* `baseId.withTag("bucket", bucket).withTag("statistic", "max")`
* `baseId.withTag("bucket", bucket).withTag("statistic", "count")`
* `baseId.withTag("bucket", bucket).withTag("statistic", "totalTime")`
* `baseId.withTag("bucket", bucket).withTag("statistic", "totalOfSquares")`

If it wasn't already this way, then we might rethink how they were modeled. Right now we don't want to break compatibility by changing the representation. Also, for a BucketTimer the most common operation is just a group by or query restriction. So it doesn't really need a custom operator and can just be thought of as another dimension in terms of how it is used. At least that is my current thinking.

**PercentileTimer**

The PercentileTimer is just a regular timer plus a set of counters that can be used to estimate the percentile.

* `baseId.withTag("statistic", "max")`
* `baseId.withTag("statistic", "count")`
* `baseId.withTag("statistic", "totalTime")`
* `baseId.withTag("statistic", "totalOfSquares")`
* `baseId.withTag("percentile", percentile)`

Since it is additive and needs a custom operator this proposal is to change the last one to:

* `baseId.withTag("statistic", "percentile").withTag("percentile", percentile)`

That way the percentile capability could be detected on the type when querying the set of available statistics.

> So, they now have the extra bucket tag and do not have the underlying ones, which is very confusing...

I'm not sure what you mean by "do not have the underlying ones". Can you given an example?

**Comment by pparth** [comment]
i just see https://github.com/Netflix/spectator/blob/master/spectator-api/src/main/java/com/netflix/spectator/api/histogram/BucketTimer.java. I cannot find any other BucketTimer implementation; maybe i am missing something. This implementation just adds the bucket tag.

**Comment by brharrington** [comment]
@pparth It adds the `bucket` tag to the id it uses to look up a normal timer:

```java
return registry.timer(id.withTag("bucket", bucket));
```

The regular timer will have the `statistic` tags on it.

**Comment by pparth** [comment]
Ah yes. It will take the timer from the registry. Got it.

**Comment by copperlight** [comment]
I like the first proposal for the following two reasons:

* It makes an unofficial type identification technique formal and it adds coverage for conceptual types that did not have it.
* It is efficient, because it does not add new tags and it makes few changes to an existing tag, which means that there will be minimal change management to implement this internally.

There are two things that I don't like about the proposal:

* You need to have or remember a mapping of the statistic to the conceptual types.  This will be handled for the typical case by our internal UI tools, but this does not help people working with the raw APIs.  To the extent that we can make the statistic tag values be closer to the names of the conceptual types, then this will be mitigated somewhat.
* It does not provide the user with the ability to annotate metrics.  One of the more common complaints we get about Atlas metrics is that users do not know what they are supposed to represent.  We have been solving this internally by creating metrics glossaries, which is a reasonable starting point, but it requires cross-referencing your current work in the UI tools. Exposing the conceptual types means that you can at least know that a metric is a rate-per-second versus a gauge, but this still will not tell you what the metrics represent.

As an alternate proposal, what if we add two tags to the reserved namespace, that are explicitly used to identify the conceptual type and provide a metric unit annotation?

* nf.metricType = (,Counter, Gauge, DistributionSummary, ...,),:in
* nf.units = (,"requests per second", "queue depth", "seconds since last success", ...,),:in

The advantages of this approach are:

* The conceptual metric type becomes easily searchable with the Tags API - you don't need to maintain a mapping.
* There is a means to describe what a metric represents.  If we allow this, then some additional thought would have to go into how we validate these strings and how we allow users to modify them.  For example, counter units should be "X per second" or "X per millisecond", depending on whether or not we allow people to change the units.  Gauge units could be more flexible.
* These tags are used for presentation of information, which means that they can be easily added to graph axes, and the addition of these tags would not break existing queries.

The disadvantages of this approach are:

* There is duplication of information between the nf.metricType and statistic tags, and it does not address the inconsistent use of the statistic tag.
* There are likely to be some inefficiencies in indexing these new tags, with the allowance of a variety of values for the nf.units tags.
* Opening up the nf.units tag to users for annotation purposes may result in data quality issues.

**Comment by brharrington** [comment]
The units stuff is a quagmire in its own right and I think it is out of scope here. I would suggest filing a separate issue to discuss that if you want to follow up.

> As an alternate proposal, what if we add two tags to the reserved namespace, that are explicitly used to identify the conceptual type and provide a metric unit annotation?
>
> * nf.metricType = (,Counter, Gauge, DistributionSummary, ...,),:in

Minor note, the `nf.` prefix is meant for Netflix infrastructure type tags. The typing is probably more appropriate for the `atlas.` namespace.

The problem with this approach is that it gets messy to identify the type and maintain it accurately across various operations. The simplest example, is that Timer is a composite type and also has a Counter. It is often useful to see the counter aspect when listing counters available for an app which works using the statistic model. The statistic model gives us both the type information as well as the set of capabilities that you have available.

As another example, consider a source like cloudwatch where we may only be able to produce `totalTime` and `count` when mapping it in. Would that be a metricType of Timer? So the UI or other tooling knows that it has a timer and can perform `:dist-avg`. With the statistic model we know what is available. If a `max` statistic comes back, then `:dist-max` is now supported. If `totalOfSquares` is available, then `:dist-stddev` can be used.

Further, the metricType can potentially break due to rollups if you are more specific and have types like PercentileTimer or BucketTimer. Lets say I rollup the bucket dimension or drop the percentile counters, the metricType for those is now wrong. With the statistic approach that capability is just dropped from the list.

**Comment by svachalek** [comment]
[hello OSS community, I am one of the primary engineers for the Atlas UI we use internally]

I like that the UI would get additional information from a tag it already checks extensively. Knowing counters from gauges is a useful thing as it gives a unit (rate per second) and indicates the advisability of :per-step (practically mandatory with :integral of counters, meaningful on counters anyway, probably silly on gauges).

Querying for specific types of metrics is probably also useful too, although I'm not sure of the demand. I can see searching for a name, finding too many matches, and then thinking "I want the one that has percentiles". Starting from the outset with "I want to find a distribution summary" seems less likely, although perhaps "I want to compare a couple of distributions" and then searching the narrowed-down list makes sense.

I would tend to agree that unit is best handled as a separate problem, although things get a little murky in that the only difference between some of these (totalAmount/totalTime) is the implicit unit involved.  Knowing units opens up other checks (different units should likely not be aggregated,  probably should default to separate axes). The implicit "seconds" unit of many of these allows for that, and could be augmented with a separate unit tag for gauges and other types.

As for combining duration/interval, seems reasonable to do and I like keeping the system simple but I'm not sure it's worth breaking queries for the sake of that.

**Comment by brharrington** [comment]
@svachalek replies inline:

> Querying for specific types of metrics is probably also useful too, although I'm not sure of the demand.

It is used in some of the UIs. For one supported by our team see the metrics page on the base server admin. It has one tab per type.

> As for combining duration/interval, seems reasonable to do and I like keeping the system simple but I'm not sure it's worth breaking queries for the sake of that.

IntervalCounter has little usage at this point, so it can be done with minimal pain. @dmuino also mentioned when I talked with him merging makes sense. So I'll assume that is the general direction we are planning to go for that question.

> The percentile type would need the presence of totalTime or totalAmount to figure understand what type it is extending. Alternatively we could make the statistic something like percentileTimer and percentileDistSummary.

Regarding this point, do you have a strong opinion one way or the other?

**Comment by svachalek** [comment]
Using totalAmount and totalTime would be ideal as that particular time series is equivalent to the one coming out of any timer or distribution.

**Comment by brharrington** [comment]
Changes discussed here will go out with spectator 0.57.0.

**Comment by pparth** [comment]
@brharrington  so, can we have a final description/documentation of the final set of changes?

**Comment by brharrington** [comment]
@pparth I'll add a page to the wiki.
