### ISSUE TITLE
detail long term plan for offset variants

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#64]
We have considered the list for deprecated for a while, but it might be more convenient for some use-cases. See discussion in: https://github.com/Netflix/atlas/pull/62. When we get around to advertising deprecated usage and trying to phase it out we should have a good story around it.

**Comment by matschaffer** [comment]
One idea that comes to mind is prohibiting use of deprecated forms without an additional `deprecated=true` query param.

**Comment by brharrington** [comment]
I think it would need to have at least some phase where user's were warned they were using something deprecated so they could transition off. We have talked about adding some notices to graph images so users can actually see it for a while. The harder issue is for programmatic access because there isn't a user looking at something to notice and just causing it to break seems a little extreme. So we don't really have a good scheme for deprecations right now. Historically it has just been internal cat herding and we try to keep it rare.

**Comment by matschaffer** [comment]
Is alerting slated for OSS? If so perhaps a "deprecatedQueries" counter that the operator could monitor.

**Comment by brharrington** [comment]
Overtime most of it should get open sourced. Tentative list is in the overview:

https://github.com/Netflix/atlas/wiki/Overview#ecosystem

Some sort of overall counter to track it is a good idea. Not sure how useful it would be as an alert, other than maybe to prevent or notice an occasional use after it has mostly been shutoff. The alert might be more interesting if it could get targeted to the team with the deprecated usage, but we don't generally have a good way to know owns or is responsible for updating a particular query use-case.

**Comment by matschaffer** [comment]
True. Maybe both are in order. Start by counting them. Then in the next
release require a param. That way the operator can be the first line of
defense but barring that the end user will eventually be forced to make
updates to their queries.

**Comment by brharrington** [comment]
Closing for now. Unless it becomes problematic for some reason in the future, there is no plan to remove to avoid breaking compatibility with many existing expressions.
