### ISSUE TITLE
Group by aggregation limit validation

### ISSUE THREAD

**Issue by davecromberge** [Netflix/atlas#684]
When exceeding the max-lines limitation defined by the memory database the behaviour observed is misleading.  The api responds with a 503 status code after about 10 seconds (akka timeout):
```
The server was not able to produce a timely response to your request. Please try again in a short while!
```

I believe this is because the `check` function within `LimitedAggregateCollector` results in an `IllegalArgumentException` which will be handled within the actor code (see FaultHandling trait in akka).  This does not give the GraphRequestActor instance a chance to gracefully deal with the exception, and I believe this is problematic.  From a consumer's perspective, it is better to return an error immediately instead of eventually responding with a 503 which gives the impression that the server is too busy and under high load.  Also, it gives the consumer the option of handling the error in a way that makes sense for them.  

I have made some changes to the code to propagate the error to the graph actor, which instead produces this api error:
```
{"type":"error","message":"IllegalArgumentException: requirement failed: too many lines: 3 > 2"}
```
- Note that the max-lines is artificially low (2) to replicate the issue.

I haven't proposed my changes as a PR because they are not production quality and I think there is probably a better way to handle this case.  I primarily would like your input on this issue, and if you agree I can help provide a failing test case toward a solution.

My changes can be found here:
https://github.com/Netflix/atlas/compare/master...davecromberge:runtime-exception?expand=1

**Comment by brharrington** [comment]
Thanks for the report. I was able to reproduce and will take a look at your branch. Also I checked and the error gets bubbled up on our main internal stack, so I need to look at what the difference is there.

**Comment by davecromberge** [comment]
For the record, I found the issue on the 1.6-rc6 branch. Am interested in how you will fix this because I suspect in the case that the actor has unhandled exceptions this will be placed as a message on deadletters. I did notice some spectator metrics about deadletters from an unregistered originator.

**Comment by davecromberge** [comment]
thanks @brharrington fix looks good 👍
