### ISSUE TITLE
interner in ExpressionSplitter never cleans up queries

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#729]
This hasn't been a problem in practice so far, but it is a leak and would cause problems if the set of queries changes enough over time.

**Comment by krutsko** [comment]
@brharrington could it be related to https://github.com/Netflix/atlas/issues/737 ?
We have a lot of queries to graph API with various time parameters (&s= &e=).

**Comment by brharrington** [comment]
@krutsko I don't think so based on the histogram.
