### ISSUE TITLE
add docs for running cloudwatch poller

### ISSUE THREAD

**Issue by brharrington** [Netflix/atlas#760]
We run this internally, but it isn't documented on the wiki. Requested by @pparth.

**Comment by brharrington** [comment]
Note, we should probably cover two scenarios:

1. Running as an independent service. This is what we do internally.
2. Running inline with the storage server. This should be possible by adding the configuration and having it go direct to localhost, but I haven't ever tried it.

**Comment by pparth** [comment]
Anything new about that? Even without documentation, would it be possible for the OOS version to enable CloudWatch metrics polling?

**Comment by brharrington** [comment]
The way we run it is by building a package with the `com.netflix.atlas_v1:atlas-module-cloudwatch_2.12` dependency and helper modules to integrate into Netflix. There are some examples of this in the [iep-apps](https://github.com/Netflix-Skunkworks/iep-apps) project. The config we use is an `application.conf` like:

```
atlas {

  webapi {
    main {
      port = 7101
    }
  }

  akka {
    api-endpoints = [
      "com.netflix.atlas.akka.HealthcheckApi",
      "com.netflix.atlas.akka.ConfigApi"
    ]
  }

  poller {
  
    frequency = 56s

    sink {
      uri = "http://localhost:7101/api/v1/publish"
    }
  
    pollers = [
      {
        name = "cloudwatch"
        class = "com.netflix.atlas.cloudwatch.CloudWatchPoller"
      }
    ]
  }

  cloudwatch.tagger {
    class = "com.netflix.atlas.cloudwatch.NetflixTagger"

    common-tags = [
      {
        key = "nf.region"
        value = ${netflix.iep.env.region}
      },
      {
        key = "nf.account"
        value = ${netflix.iep.env.insight-account-id}
      }
    ]

    netflix-keys = [
      "nf.asg",
      "aws.elb"
    ]
  }

  // If there is a need to customize the set of metrics collected
  //cloudwatch.categories = [
  //  "ec2",
  //  "elasticache",
  //  "elb",
  //  "lambda"
  //]

}

netflix.iep.aws.cloudwatch {
  client {
    use-throttle-retries = true
    max-error-retry = 10
  }

  credentials {
    role-arn = "arn:aws:iam::"${netflix.iep.env.insight-account-id}":role/AtlasCloudWatch"
    role-session-name = "cloudwatch"
  }
}
```

**Comment by brharrington** [comment]
CloudWatch polling was moved out (#1327) as it is not related to the core storage.
