### ISSUE TITLE
Consolidation functions not working correctly with rewrites

### ISSUE THREAD

**Issue by davecromberge** [Netflix/atlas#763]
This issue may be related to https://github.com/Netflix/atlas/issues/584 and can be replicated on v1.6.0-rc.8

Expectation:
------------

I expect that it is reasonable to use average to aggregate across series within a step, and then consolidate to downsample multiple averages in that step interval.  An example of this would be if I have a high density graph that is very narrow (small width).

For example:
```
name,sys.cpu.pct,:eq,service,system,:eq,:and,:avg,:cf-sum"
```

Should yield the following stack (ignoring rewrites):
```
{
    "program": [],
    "context": {
      "stack": [
        "name,sys.cpu.pct,:eq,service,system,:eq,:and,:avg,:cf-sum"
      ],
      "variables": {}
    }
}
```

Actual:
-------

```
name,sys.cpu.pct,:eq,service,system,:eq,:and,:avg,:cf-sum"
```
results in an error from the interpreter:

```
{"type":"error","message":"IllegalStateException: no matches for word ':cf-sum' with stack [NamedRewrite], candidates: [AggregateFunction -- DataExpr]"}
```

`CfWord#matcher` looks like a consolidation function matcher needs to follow an `AggrType`:
```scala
sealed trait CfWord extends SimpleWord {

    def cf: ConsolidationFunction

    protected def matcher: PartialFunction[List[Any], Boolean] = {
      case AggrType(_) :: _ => true
    }

    protected def executor: PartialFunction[List[Any], List[Any]] = {

    // ...contents elided
  }
```

Is this expected behaviour, and if so, do you recommend the given workaround in the aforementioned issue?   If you can suggest a code fix, I am happy to attempt it.

**Comment by brharrington** [comment]
Thanks for the report. It is similar to #584 but in this case it doesn't work if I expand the group by. For example I can reproduce after expanding:

```
name,sps,:eq,:and,:dup,:sum,:swap,:count,:div,:cf-sum
```

To make this work it would likely need variants of the `:cf-*` operators that rewrite to apply the consolidation to the aggregate function. Here is how that works for group by:

https://github.com/Netflix/atlas/blob/master/atlas-core/src/main/scala/com/netflix/atlas/core/model/MathVocabulary.scala#L255
