### ISSUE TITLE
如何知道atlas能够输出哪些Metrics？

### ISSUE THREAD

**Issue by 13940344135** [Netflix/atlas#837]
如何知道atlas能够输出哪些Metrics？

**Comment by 13940344135** [comment]
Thank you very much for your answer. I'm doing a comparison of various monitoring systems. But I don't know Stack Language. Can you tell me? Query all metrics statement how to write?

**Comment by 13940344135** [comment]
![1528088354 1](https://user-images.githubusercontent.com/30135674/40899028-44d92514-67f7-11e8-9b4b-1e9aac7c4a5a.png)
As shown in the figure, my atlas has been able to collect jvm information, but I do not know how to query out all metrics

**Comment by brharrington** [comment]
> But I don't know Stack Language. Can you tell me? Query all metrics statement how to write?

Querying everything would be done something like `:true,:all`, but this isn't very useful. We do not really optimize for a user to get everything.

> http://localhost:7101/api/v1/tags/name
> Is this all?

That would be all of the distinct name values. The tags API gets used with our internal UI and dashboard tools to allow the user to drill into the data. It isn't listing the tag maps for everything, but allowing the user to project the keys or values for a base query.

For example, suppose you select app `StvDelivery` then the UI would use a base query like `app,StvDelivery,:eq` and run a [tag query](https://github.com/Netflix/atlas/wiki/Tag) to see value. To see all metric names for that app it would be:

http://localhost:7101/api/v1/tags/name?q=app,StvDelivery,:eq

You could then select a name and an aggregation function to [render a graph](https://github.com/Netflix/atlas/wiki/Graph) for a particular metric:

http://localhost:7101/api/v1/graph?q=app,StvDelivery,:eq,name,jvm.memory.used,:eq,:and,:max
