### ISSUE TITLE
Alerting question: How to detect "flapping"?

### ISSUE THREAD

**Issue by davecromberge** [Netflix/atlas#838]
I would like to know if there is preferred way to detect when a series fluctuates above and below some threshold in the Atlas stack language.  Having read the wiki pages on alerting, I have tried to formulate an appropriate simple query but I do not know if this is the correct thing to do.

I have a metric called `sys.load.1` (blue series line) , where I want to generate an alert signal if it exceeds `0.5` for a period of two minutes (brown series line).  Finally, I would like to determine if this alert signal has alternated between 0 and 1 successively for a period of roughly 20mins (the green flap series signal line).

![image](https://user-images.githubusercontent.com/164431/41103339-d0392ef4-6a60-11e8-8990-2700cf519f7e.png)

My query so far looks like this:
```
api/v1/graph?
   e=now
   &s=e-1h
   &q=
      name,sys.load.1,:eq,
      cloud.instance.id,i-04fee6cbbbad3b714,:eq,
      :and,
      :max,
      :dup,
      0.5,:ge,
      4,:rolling-count,
      4,:ge,
      :dup,
      10,:rolling-count,
      10,:ge
```
Where I have encoded 4 as the rolling count, I mean to say the last 4 points = 2min, and 20min = 10 * 2min windows etc, given a 30s step interval.

To give a true signal for alternate values, my last condition would instead be:

```
   10,:rolling-count,
   5,:eq
```
But my concern is that this is too naive.  I would be grateful for any assistance.

**Comment by copperlight** [comment]
I am not sure why alerting on alternating values of the rolling count
result is useful. It sounds like it is more important to know that
sys.load.1 has exceeded an acceptable value some number of times within a
20 minute window. In which case, extend your rolling-count window and
increase your threshold for that.

The nature of the rolling-count function is that it only increments the
result if the input is greater than zero, so any values of that function
which are less than the the size of the window indicates that there was
some flapping going on.

**Comment by davecromberge** [comment]
Thanks @copperlight, that actually sounds far simpler than trying to window within the rolling count. The intention was to serve as a signal that may potentially tolerate a certain amount of missing values within a windowed period.  So, if the rolling-count was over the entire period, you may have flapping right at the end of the window, but because the beginning of the window had missing data/values, it's possible to miss this fact. But this is admittedly contrived and probably more trouble than it's worth.
Considering your suggestion, I would like to avoid regarding a constant 1 signal as a flapping signal, because this would obviously max out the rolling count.
I imagine it's then a matter of tuning the rolling count to have both `:gt` and `:lt` thresholds so that the flap detection does not generate too many false positives/negatives.
Thanks again for the help.
