### ISSUE TITLE
How to determine the number of unique metrics in storage

### ISSUE THREAD

**Issue by davecromberge** [Netflix/atlas#848]
I would like to know how I determine the number of unique `TaggedItem`s exist that exist at any point in time?

Until this point, I have been using the `atlas.block.arrayCount`  value from the `Blockstats` module.  The problem with this count is that it will include closed blocks that did not compress into constant blocks, float array blocks etc and remained as array blocks.  This leads to a figure that does not truly reflect the number of unique metrics.

I have noticed that the database periodically queries the index size in the log, like this:
```
2018-07-09T11:29:11.069 INFO  [MemoryDatabaseRebuildIndex] com.netflix.atlas.core.db.MemoryDatabase: rebuilding metadata index
2018-07-09T11:29:12.745 INFO  [MemoryDatabaseRebuildIndex] com.netflix.atlas.core.db.MemoryDatabase: done rebuilding metadata index, 199998 metrics
```
Does the `atlas_index_pendingupdates` gauge accurately reflect the size?  If not, given that the index size is consulted already during the `rebuild` task, in the `MemoryDatabase`, this seems like the most natural place to record this value as a gauge.  I'm happy to do a pull request if there is there is no better alternative.

**Comment by brharrington** [comment]
Internally we have gauge `atlas.db.size` that reports the index size. I thought it was part of the OSS, but looks like it is coming from an internal component. Feel free to submit a PR or I'll take a look sometime this week.
