### ISSUE TITLE
How does cluster management work?

### ISSUE THREAD

**Issue by jfz** [Netflix/atlas#953]
Hi,
I'm trying to understand how cluster management work. More specifically:
1. how cluster is bootstrapped
2. how data / query is routed to the right node
3. failure recovery flow
I went through the Wiki and couldn't find much information about this. 

Thanks,
Tim

**Comment by brharrington** [comment]
Sorry about the delayed response, I overlooked the original notification.

The clustering aspects used at Netflix are not fully open source at this time. The main reason is we need to abstract some aspects so it is usable outside of Netflix. Thus far we have not had the bandwidth to prioritize it as it doesn't further internal needs. For the specific questions:

1. We have an internal declarative deployment system that is used to spin up the various parts we need. Conceptually it is kind of similar to [Terraform](https://www.terraform.io/) except that it can also handle transitions to a new state. So we can change the desired state and it will figure out how to cleanly transition from the current state to the new desired state. There are definitions for what the various parts of the stack look like that we can clone and adapt for new stacks. This diagram gives a high level view of what one of our stacks looks like:

![atlas-architecture](https://user-images.githubusercontent.com/1289028/50348920-0808cc80-04ef-11e9-8823-994a871751b8.png)

2. We use a uniform hash based sharding policy (see [overview/slide-38](http://netflix.github.io/atlas/slides/atlas_overview.pdf#page=38)). This gives us uniform data distribution and avoids hotspots where there is a lot more data for one shard. Also many of our queries are aggregations across hundreds of thousands of time series so this gives us better distribution of the computation. On the ingestion flow we have a publish cluster that uses slot assignments for each instance in an auto-scaling group to know how to map data to a particular instance. At query time we fanout to all shards to get the partial aggregates. The query layer has a number of policies we can use to depending on what tradeoffs we want (brief summary see [overview/slide-46](http://netflix.github.io/atlas/slides/atlas_overview.pdf#page=46)). For example we can use round-robin across mirrors to increase the overall query volume, a speculative execution to reduce latency, or a correcting policy where we query both and merge for the best consistency.

3. There is a bit of information in the overview slides (see [overview/slide-41](http://netflix.github.io/atlas/slides/atlas_overview.pdf#page=41)). On the publishing side we send to multiple in-memory mirrors. For long term we do a correcting merge step across all of the mirrors. For short-term we can also choose to do a correcting merge at query time if that is desirable compared to other tradeoffs. 

Note, for our uses we focus on operational insight not business insight. So our primary focus is being able to answer what is happening right now and we would rather have some information than nothing so in the middle of an outage teams can make reasonable decisions as quickly as possible to reduce customer impact. With business insight there is usually a much stronger focus on avoiding data loss. Our clustering is rather simple, but this has given us a big reliability benefit. In particular:

* Having few dependencies means so it is less likely we have correlated failures where the monitoring system is down at the same time as other key systems like Kafka, ZooKeeper, Cassandra, etc. When there is a big customer facing outage is when we most want the monitoring system to be working correctly.
* There is a bit of state needed to maintain the slot assignments we use to shard data. However, if the system that provides that fails, we have cached views and can still operate without problems indefinitely as long as the instances are not replaced. If some instances are replaced it would be a partial degradation of data for those shards until the slotting service was brought back online.

There is a company called [Outlyer](https://www.outlyer.com/) that uses Atlas internally. They have some [talks](https://www.outlyer.com/blog/why-not-to-build-a-time-series-database/) about their usage and how they do clustering that might also be useful to you. Their use-cases are a bit different so they went for different tradeoffs compared to what we do.

**Comment by brharrington** [comment]
That is correct. This can apply a small overhead for some queries that aggregate over a small number of time series. However, for many of our common queries that are aggregating over a large number there will be a subset of data on each shard and this gives us better distribution of the computation as well as the data. It also keeps the sharding logic simple and avoid needing more complex infrastructure to know how to route the queries which helps with our reliability goals.
