### ISSUE TITLE
Support for controlling units formatting

### ISSUE THREAD

**Issue by haydenzone** [Netflix/atlas#991]
Under certain circumstances which are unclear to me, values on the y axis will sometimes be formatted 99770.00m instead of just showing 99.77. It'll also sometimes show other measurements relative to some base value (see attached screenshot). It would be nice to have this configurable. At a bare minimum, I'd like to be able to just turn it off.
<img width="93" alt="graph" src="https://user-images.githubusercontent.com/2296601/52826654-a2f8cf80-3076-11e9-9ce6-5d8c59d09bb3.png">

**Comment by brharrington** [comment]
It will try to automatically choose a scale that makes sense for the range of the values. Making it configurable would be a bit tricky to get right as the user could choose something that conflicts with other constraints and we need to sort out how that would get resolved. If you have some specific examples of ranges that the current automatic selection is doing poorly on we can take a look at adding those as additional test cases and improving the logic.

The image shown is an offset notation. It gets used when the graph is zoomed in to a narrow range and the number of significant digits needed to show the delta between major ticks marks would not fit within the space allotted for the tick labels.

**Comment by brharrington** [comment]
Example that produces similar results to the sample image:

```
/api/v1/graph?q=99.99&u=100&l=99.938845
```

**Comment by haydenzone** [comment]
Here's an example where the relative label was unhelpful and made the graph hard to read. 

graph?backend=SOME_URL&g.q=name,apache.http.request,:eq,%0Astatus,5xx,:eq,:and,%0Astatistic,count,:eq,:and,%0A%0Aname,apache.http.request,:eq,%0Astatistic,count,:eq,:and,%0A%0A:fdiv,%0A-1,%20:fmul,%0A1,%20:fadd,%0A100,%20:fmul&g.title=Apache%205XX%20%2F%20Requests&g.o=0&g.s=e-3h&g.e=now-5m&g.tz=US%2FPacific&g.no_border=1&g.stack=0&g.w=788&g.h=249&g.layout=iw&g.refresh=1550162843146&mode=png&g.u.0=100&g.stack.0=0&g.o.0=0&tick_labels=decimal

produces

![image](https://user-images.githubusercontent.com/2296601/52873624-51972180-3104-11e9-8191-cdf62212cece.png)

If it would just say "100.00" or "99.90" that would be sufficient.

**Comment by brharrington** [comment]
Change in #994 suffices for now. Currently there is no plan to introduce additional configuration knobs for this.
